const redisKey = {
  userDetail: 'cache:user_detail:%d',
  userProblemResultStats: 'cache:user_problem_result_stats:%d',
  userSolutionCalendar: 'cache:user_solution_calendar:%d_%d',
  userGroups: 'cache:user_groups:%d',
  problemDetail: 'cache:problem_detail:%d',
  solutionDetail: 'cache:solution_detail:%d',
  contestDetail: 'cache:contest_detail:%d',
  contestProblems: 'cache:contest_problems:%d',
  contestProblemResultStats: 'cache:contest_problem_result_stats:%d',
  contestProblemResultStatsWithFrozen: 'cache:contest_problem_result_stats_frozen:%d',
  contestRanklist: 'cache:contest_ranklist:%d_%d',
  contestUserDetail: 'cache:contest_user_detail:%d',
  userContests: 'cache:user_contests:%d',
  competitionDetail: 'cache:competition_detail:%d',
  competitionProblems: 'cache:competition_problems:%d',
  competitionProblemResultStats: 'cache:competition_problem_result_stats:%d',
  competitionProblemResultStatsWithFrozen: 'cache:competition_problem_result_stats_frozen:%d',
  competitionStandardRanklist: 'cache:competition_srk:%d_%d',
  competitionUsers: 'cache:competition_users:%d',
  competitionUserDetail: 'cache:competition_user_detail:%d_%d',
  competitionSettingDetail: 'cache:competition_setting_detail:%d',
  competitionNotifications: 'cache:competition_notifications:%d',
  competitionRanklist: 'cache:competition_ranklist:%d_%d',
  topicDetail: 'cache:topic_detail:%d',
  postDetail: 'cache:post_detail:%d',
  tagList: 'cache:tag_list',
  problemTags: 'cache:problem_tags:%d',
  setDetail: 'cache:set_detail:%d',
  groupDetail: 'cache:group_detail:%s',
  groupMemberList: 'cache:group_member_list:%s',
  ratingContestDetail: 'cache:rating_contest_detail:%d',
  ratingContestDetailForCompetition: 'cache:rating_contest_detail_competition:%d',
  judgerLanguageConfig: 'cache:judger_language_config',
  solutionJudgeInfo: 'cache:solution_judge_info:%d',
  userPermissions: 'cache:user_permissions:%d',
  fieldDetail: 'cache:field_detail:%d',
  balloonDetail: 'cache:balloon_detail:%d',
  verificationCode: 'verification:code:%s',
  recordUserUpload: 'record:user_upload:%d',
  recordUserCreateGroup: 'record:user_create_group:%d',
  userACStats: 'stats:user_ac:%s',
  userASProblemsStatsRunInfo: 'stats:user_a_s_problems_run_info',
  userAcceptedProblemsStats: 'stats:user_accepted_problems:%d',
  userSubmittedProblemsStats: 'stats:user_submitted_problems:%d',
  activeUserCountStats: 'stats:active_user_count',
  contestRankData: 'temp:contest_rank_data:%d',
  competitionRankData: 'temp:competition_rank_data:%d',
  judgeStatus: 'status:judge_status:%d', // {judgeInfoId}
  /** @deprecated */
  solutionJudgeStatus: 'status:solution_judge_status:%d',
  contestRatingStatus: 'status:contest_rating_status:%d',
  competitionRatingStatus: 'status:competition_rating_status:%d',
  rateIp: 'rateIp:%s:%s', // {interfaceName} {ip}
  rateUser: 'rateUser:%s:%d', // {interfaceName} {userId}
  session: 'session:%d:%s', // {userId} {sessionKey}
  lockCompetitionBallonCalc: 'lock:competition_balloon_calc:%d', // {competitionId}
  asyncSolutionProblemStatsTasks: 'async:solution_problem_stats_tasks',
  asyncSolutionUserStatsTasks: 'async:solution_user_stats_tasks',
};

export default redisKey;
export type IRedisKeyConfig = typeof redisKey;
