export enum ECompetitionLogAction {
  Login = 'Login',
  Logout = 'Logout',
  SignUp = 'SignUp',
  ModifySelfParticipantInfo = 'ModifySelfParticipantInfo',
  AuditParticipant = 'AuditParticipant',
  ConfirmEnter = 'ConfirmEnter',
  ConfirmQuit = 'ConfirmQuit',
  UpdateDetail = 'UpdateDetail',
  UpdateSettings = 'UpdateSettings',
  UpdateProblemConfig = 'UpdateProblemConfig',
  SubmitSolution = 'SubmitSolution',
  RejudgeSolution = 'RejudgeSolution',
  BatchCreateUser = 'BatchCreateUser',
  CreateUser = 'CreateUser',
  UpdateUser = 'UpdateUser',
  RequestPassword = 'RequestPassword',
  RandomAllUserPasswords = 'RandomAllUserPasswords',
  CreateNotification = 'CreateNotification',
}
